In [75]:
import numpy as np
import pandas as pd


## Datatype and Attributes


In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,2,3],
              [4, 5, 6.5]])
a3 = np.array([[[1, 2 ,3],
              [4, 5, 6],
              [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
               [16, 17, 19]]])

In [5]:
a2


array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 19]]])

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a2.ndim

2

In [9]:
# Creat Numpy Arrays

In [11]:
ones = np.ones((2, 3))

In [12]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ones.dtype

dtype('float64')

In [14]:
type(ones)

numpy.ndarray

In [17]:
zeros = np.zeros((2,3))

In [18]:
zeros.dtype

dtype('float64')

In [19]:
range_array = np.arange(0, 10 , 2)

In [20]:
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size = (3,5))

In [22]:
random_array

array([[6, 7, 6, 3, 5],
       [3, 5, 6, 1, 3],
       [4, 0, 1, 2, 0]])

In [24]:
random_array2 = np.random.random((5,3))

In [25]:
random_array2

array([[0.93666016, 0.17447782, 0.06743618],
       [0.77315661, 0.83067138, 0.68542779],
       [0.45232306, 0.7596905 , 0.27426142],
       [0.9392757 , 0.35975336, 0.49659298],
       [0.85867962, 0.5153057 , 0.52151779]])

In [26]:
random_array3 = np.random.rand(5,3)

In [27]:
random_array3

array([[0.66463788, 0.20618319, 0.70275579],
       [0.02989106, 0.84510637, 0.34300974],
       [0.64551307, 0.3062365 , 0.94460003],
       [0.55239484, 0.7104491 , 0.98024484],
       [0.65556198, 0.12786007, 0.9104618 ]])

In [31]:
np.random.seed(0)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
# Viewing arrays and matrices

In [32]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1., 2., 3.])

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
a4 = np.random. randint(10, size = (2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [39]:
a4[:, :, :, :2]

array([[[[6, 7],
         [5, 9],
         [3, 0],
         [2, 3]],

        [[3, 3],
         [9, 9],
         [3, 2],
         [0, 4]],

        [[8, 4],
         [8, 1],
         [9, 3],
         [0, 3]]],


       [[[4, 6],
         [4, 4],
         [7, 5],
         [5, 9]],

        [[0, 1],
         [0, 3],
         [5, 9],
         [2, 9]],

        [[2, 3],
         [9, 1],
         [2, 3],
         [0, 6]]]])

In [40]:
# Manipulating and comparing arrays

In [41]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [42]:
a1 *a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [43]:
## Aggregation


In [44]:
list1 = [1,2,3]

In [45]:
sum(list1)

6

In [46]:
np.sum(a1)

6

In [48]:
massive_array = np.random.random(1000000)

In [49]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

220 ms ± 29.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.07 ms ± 412 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [50]:
np.mean(a2)

3.5833333333333335

In [51]:
np.std(a2)

1.8352262954621035

In [53]:
np.max(a2)

6.5

np.var(a2)

In [54]:
np.var(a2)

3.368055555555556

In [55]:
np.sqrt(np.var(a2))

1.8352262954621035

In [56]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.5]]])

In [58]:
a2_reshape = a2.reshape(2,3,1)

In [59]:
a2_reshape *a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 123.5]]])

In [60]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3. , 6.5]])

In [61]:
a2.T.shape

(3, 2)

In [62]:
# Dot Product

In [68]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [67]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [69]:
np.dot(mat1.T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [70]:
## Dot Product Example

In [73]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size = (5, 3))

In [76]:
weekly_sales = pd.DataFrame(sales_amounts,
                           index = ["Mon" , "Tues" , "Wed", "Thurs", "Fri"],
                           columns = ["Almond Butter", "Penut Butter", "Cashew Butter"] )

In [77]:
weekly_sales

Almond Butter  Penut Butter  Cashew Butter
Mon               12            15              0
Tues               3             3              7
Wed                9            19             18
Thurs              4             6             12
Fri                1             6              7

In [78]:
# create prices array
prices = np.array([10, 8, 12])

In [80]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index = ["Price"],
                            columns = ["Almond Butter", "Penut Butter", "Cashew Butter"] )

In [81]:
butter_prices

Almond Butter  Penut Butter  Cashew Butter
Price             10             8             12

In [82]:
total_sales = prices.dot(sales_amounts.T)

In [83]:
total_sales

array([240, 138, 458, 232, 142])

In [84]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [86]:
weekly_sales["Total ($)"] = daily_sales.T

In [87]:
weekly_sales

Almond Butter  Penut Butter  Cashew Butter  Total ($)
Mon               12            15              0        240
Tues               3             3              7        138
Wed                9            19             18        458
Thurs              4             6             12        232
Fri                1             6              7        142